/*
 * mailViewer.java
 *
 * Created on 1 febbraio 2006, 20.30
 */

package spampiGUI;
import javax.swing.*;
import java.io.*;
import core.*;

/**
 *
 * @author  Stefano Bianchini
 */
public class mailViewer extends javax.swing.JFrame {
    private aboutFrame a;
    /** Creates new form mailViewer */
    public mailViewer(aboutFrame a) {
        initComponents();
        this.a=a;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FromLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        SubjectLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMail = new javax.swing.JMenuItem();
        FileMenuSeparator = new javax.swing.JSeparator();
        ExitMenu = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setTitle("SpamPI Mail Viewer 0.1beta");
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        FromLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spampiGUI/nav_clients.gif")));
        FromLabel.setText("From:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 17);
        jPanel2.add(FromLabel, gridBagConstraints);

        jTextField1.setEditable(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 17);
        jPanel2.add(jTextField1, gridBagConstraints);

        SubjectLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spampiGUI/btn_show-all_bg.gif")));
        SubjectLabel.setText("Subject:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 17);
        jPanel2.add(SubjectLabel, gridBagConstraints);

        jTextField2.setEditable(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 17);
        jPanel2.add(jTextField2, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spampiGUI/session_admin.gif")));
        jLabel1.setText("Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 17);
        jPanel2.add(jLabel1, gridBagConstraints);

        jTextField3.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 17);
        jPanel2.add(jTextField3, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(new javax.swing.border.TitledBorder("Mail Body Content"));
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Courier", 0, 12));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        FileMenu.setText("File");
        OpenMail.setText("Open Mail");
        OpenMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMailActionPerformed(evt);
            }
        });

        FileMenu.add(OpenMail);

        FileMenu.add(FileMenuSeparator);

        ExitMenu.setText("Exit");
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });

        FileMenu.add(ExitMenu);

        jMenuBar1.add(FileMenu);

        help.setText("?");
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        help.add(About);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-450)/2, 600, 450);
    }
    // </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
// TODO add your handling code here:
        a.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitMenuActionPerformed

    private void OpenMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMailActionPerformed
// TODO add your handling code here:
        final JFileChooser fc=new JFileChooser();
        //fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //fc.setBackground(new java.awt.Color(255,255,0));
        int returnVal = fc.showOpenDialog(new JDialog());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //jTextField2.setText(file.getAbsoluteFile().getPath());
            try {
            FileInputStream fis=new FileInputStream(file);
            InputStreamReader isr=new InputStreamReader(fis);
            BufferedReader br=new BufferedReader(isr);
            String mailString="";
            String line="";
            while((line=br.readLine())!=null) {
                mailString=mailString+line+"\n";
            }
            Mail m = new Mail(mailString);
            jTextArea1.setText(m.getBody());
            jTextField3.setText((m.getDate()).trim());
            jTextField2.setText((m.getSubject()).trim());
            jTextField1.setText((m.getAddress()).trim());
            }catch(Exception e){System.out.println("Error in OpenMail");}
        }
    }//GEN-LAST:event_OpenMailActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mailViewer(new aboutFrame()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JSeparator FileMenuSeparator;
    private javax.swing.JLabel FromLabel;
    private javax.swing.JMenuItem OpenMail;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    
}
