/*
 * optionGUI.java
 *
 * Created on 13 febbraio 2006, 19.32
 */

package spampiGUI;
import java.util.*;
import java.io.*;
/**
 *
 * @author  Stefano
 */
public class optionGUI extends javax.swing.JFrame {
     
    private Properties prop;
    
    /** Creates new form optionGUI */
    public optionGUI() {
        initComponents();
        this.prop = new Properties();
        try{
            FileInputStream in = new FileInputStream("SpamPIG.properties");
            prop.load(in);
            pathText.setText(prop.getProperty("pop.path"));
            serverText.setText(prop.getProperty("pop.server"));
            userText.setText(prop.getProperty("pop.user"));
            passwordText.setText(prop.getProperty("pop.passwd"));
            in.close();
        }catch(Exception e){System.out.println(e);}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        serverText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pathText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        DiscardButton = new javax.swing.JButton();

        setTitle("SpamPig Options");
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Change Options"));
        jLabel1.setText("Pop Mail Server");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 42, 6, 41);
        jPanel1.add(jLabel1, gridBagConstraints);

        serverText.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 2);
        jPanel1.add(serverText, gridBagConstraints);

        jLabel2.setText("Pop Mail User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 42, 6, 41);
        jPanel1.add(jLabel2, gridBagConstraints);

        userText.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 2);
        jPanel1.add(userText, gridBagConstraints);

        jLabel3.setText("Pop Mail Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 42, 6, 41);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Path of Spam Directory*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 42, 6, 41);
        jPanel1.add(jLabel4, gridBagConstraints);

        pathText.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 2);
        jPanel1.add(pathText, gridBagConstraints);

        jLabel5.setText("* (where Spam mails will be saved to)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 2);
        jPanel1.add(jLabel5, gridBagConstraints);

        passwordText.setFont(new java.awt.Font("Tahoma", 0, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 2);
        jPanel1.add(passwordText, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jPanel2.add(SaveButton);

        DiscardButton.setText("Discard");
        DiscardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardButtonActionPerformed(evt);
            }
        });

        jPanel2.add(DiscardButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }
    // </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
// TODO add your handling code here:
        this.prop=new Properties();
        prop.setProperty("pop.path",pathText.getText());
        prop.setProperty("pop.server",serverText.getText());
        prop.setProperty("pop.user",userText.getText());
        prop.setProperty("pop.passwd",passwordText.getText());
        try {
            FileOutputStream fos = new FileOutputStream("SpamPIG.properties");
            PrintWriter out = new PrintWriter(fos);
            prop.list(out);
            out.flush();
            javax.swing.JOptionPane.showMessageDialog(this,"Options saved successfully","SpamPig Options Message",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {System.out.println(e);}
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DiscardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardButtonActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_DiscardButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new optionGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiscardButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField pathText;
    private javax.swing.JTextField serverText;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
    
}
