/*
 * progressFrame.java
 *
 * Created on 3 febbraio 2006, 17.55
 */

package spampiGUI;

/**
 *
 * @author  Stefano Bianchini
 */
public class progressFrame extends javax.swing.JFrame {
    
    /** Creates new form progressFrame */
    public progressFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progressLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        progress = new javax.swing.JProgressBar();

        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        setTitle("SpamPI 0.1 Progress Dialog");
        setResizable(false);
        progressLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spampiGUI/progrimage.gif")));
        progressLabel.setText("SpamPI Progress Dialog");
        progressLabel.setBorder(new javax.swing.border.EtchedBorder());
        progressLabel.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(progressLabel);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        progress.setPreferredSize(new java.awt.Dimension(350, 18));
        jPanel1.add(progress, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-170)/2, 400, 170);
    }
    // </editor-fold>//GEN-END:initComponents
    //Set the value of the Progress Label
    public void setText(String text) {
        progressLabel.setText(text);
    }
    public void setMax(int max) {
        progress.setMaximum(max);
    }
    //Set the value of the Progress Bar
    public void setProgress(int percent) {
        progress.setValue(percent);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progressFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables
    
}
