/*
 * viewTheoryGUI.java
 *
 * Created on 6 febbraio 2006, 18.44
 */

package spampiGUI;
import alice.tuprologx.ide.JavaEditArea;
import java.io.*;


/**
 *
 * @author  Stefano
 */
public class viewTheoryGUI extends javax.swing.JFrame {
    
   private progressFrame pr;
    
    /** Creates new form viewTheoryGUI */
    public viewTheoryGUI() {
        pr = new progressFrame();
        pr.setText("Opening Prolog Theory, wait please");
        
        String theory="";
        String thisLine="";
        initComponents();
        JavaEditArea jEA = new JavaEditArea();
        jPanel1.add(jEA);
        jEA.setTheory(" ");
            File inFile = new File("theory.pl");

            try {
            FileInputStream fis  = new FileInputStream(inFile);
            BufferedReader in = new BufferedReader(new InputStreamReader(fis));
            //to count number of lines
            int counter = 0;
            while ((thisLine = in.readLine()) != null) {
                counter++; System.out.println(counter);
   
            }
            fis.close();
            in.close();
            
            pr.setMax(counter);
            
            FileInputStream fis2  = new FileInputStream(inFile);
            BufferedReader in2 = new BufferedReader(new InputStreamReader(fis2));
           
            
            counter=0;
            pr.setVisible(true);
            while ((thisLine = in2.readLine()) != null) {
                theory=theory+thisLine+"\n";
                pr.setProgress(counter++);
   
            }
            jEA.setTheory(theory.trim());
            fis2.close();
            in2.close();
            pr.setVisible(false);
            } catch (IOException e) {System.out.println(e);}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();

        setTitle("Prolog Theory");
        jPanel1.setLayout(new java.awt.BorderLayout());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-640)/2, (screenSize.height-480)/2, 640, 480);
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewTheoryGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
